# Generated by Django 5.2.7 on 2025-10-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_email_4b85f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_date_jo_0c802f_idx',
        ),
    ]
