# Generated by Django 5.2.7 on 2025-10-20 05:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=32)),
                ('bank_code', models.CharField(choices=[('KAKAO', '카카오뱅크'), ('KB', 'KB국민'), ('NH', '농협'), ('IBK', '기업'), ('ETC', '기타')], max_length=10)),
                ('account_type', models.CharField(choices=[('DEMAND', '입출금통장'), ('OVERDRAFT', '마이너스'), ('SAVINGS', '적금/예금'), ('ETC', '기타')], default='DEMAND', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('io_type', models.CharField(choices=[('DEPOSIT', '입금'), ('WITHDRAW', '출금')], max_length=10)),
                ('method', models.CharField(choices=[('CASH', '현금'), ('TRANSFER', '계좌이체'), ('AUTO', '자동이체'), ('CARD', '카드결제'), ('ETC', '기타')], default='TRANSFER', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.account')),
            ],
            options={
                'db_table': 'transaction_history',
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', '-created_at'], name='idx_acct_user_created'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('bank_code', 'account_number'), name='uq_bank_acct'),
        ),
        migrations.AddIndex(
            model_name='transactionhistory',
            index=models.Index(fields=['account', '-created_at'], name='idx_txn_acct_created'),
        ),
        migrations.AddIndex(
            model_name='transactionhistory',
            index=models.Index(fields=['account', 'io_type'], name='idx_txn_acct_io'),
        ),
    ]
