# Generated by Django 5.2.7 on 2025-10-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_remove_account_uq_bank_acct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('DEMAND', '입출금통장'), ('OVERDRAFT', '마이너스 통장'), ('SAVINGS', '예·적금'), ('ETC', '기타')], default='DEMAND', max_length=16),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank_code',
            field=models.CharField(choices=[('KAKAO', '카카오뱅크'), ('KB', 'KB국민'), ('NH', '농협'), ('IBK', '기업'), ('SC', 'SC제일'), ('HANA', '하나'), ('WOORI', '우리'), ('SHINHAN', '신한'), ('ETC', '기타')], max_length=16),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='method',
            field=models.CharField(choices=[('CASH', '현금'), ('TRANSFER', '계좌 이체'), ('AUTO', '자동 이체'), ('CARD', '카드 결제'), ('ETC', '기타')], default='TRANSFER', max_length=16),
        ),
    ]
