# Generated by Django 5.2.7 on 2025-10-21 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_alter_account_account_type_alter_account_bank_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'ordering': ('-created_at',)},
        ),
    ]
